/**
 * intent/contract-file.js — a human-reviewed contract as the test oracle (QB-13).
 *
 * `qb "<request>" --contract-file <path>` runs against a contract the human wrote
 * or reviewed (for example the proposed contract QB saved from an earlier run),
 * instead of one generated by the model: the test oracle is then independent of
 * the implementation-generating model. The file is normalized and validated
 * exactly like model output (criteria, registry checks, trusted arithmetic);
 * nothing is corrected. Approval records the file's SHA-256.
 */

const crypto = require('crypto');
const fs = require('fs');
const { contractFromObject } = require('./compiler');
const { approve } = require('./contract-state');

const MAX_BYTES = 256 * 1024;

/** The semantic fields QB saves for review and reads back (no trusted metadata, no approval). */
const REVIEW_FIELDS = ['goal', 'required_behavior', 'constraints', 'acceptance_criteria', 'verification_plan',
  'relevant_context', 'ambiguity_flags', 'checks', 'scope', 'constraint_policy', 'requirements', 'test_policy'];

function loadContractFile(file, request) {
  const st = fs.statSync(file);
  if (!st.isFile() || st.size > MAX_BYTES) throw new Error(`contract file must be a regular file of at most ${MAX_BYTES} bytes`);
  const buf = fs.readFileSync(file);
  const raw = JSON.parse(buf.toString('utf8'));
  if (raw && typeof raw === 'object' && raw.clarifying_question) throw new Error('a contract file cannot contain an open clarifying_question');
  const contract = contractFromObject({ ...raw, clarifying_question: null }, request);
  const sha = crypto.createHash('sha256').update(buf).digest('hex');
  return { contract, sha, approved: () => approve(contract, { via: 'contract-file', note: `sha256:${sha}` }) };
}

/** The proposed contract, as the human-reviewable file `--contract-file` reads. */
function proposalForReview(contract) {
  const out = {};
  for (const k of REVIEW_FIELDS) if (contract[k] !== undefined) out[k] = contract[k];
  out.acceptance_criteria = (contract.acceptance_criteria || []).map((a) => ({ id: a.id, criterion: a.criterion, kind: a.kind || 'behavioral', requirement_ids: a.requirement_ids || [], ...(a.preserves !== undefined ? { preserves: a.preserves } : {}) }));
  return out;
}

module.exports = { loadContractFile, proposalForReview };
