name               = "quaterback"
main               = "landing_page/_worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = "landing_page"
binding   = "ASSETS"

[[d1_databases]]
binding       = "qb-beta"
database_name = "qb-beta"
database_id   = "6bb621d5-e492-4154-bb38-a7bd567e363f"
